/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdditionRouteImport } from './routes/addition'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComprendsRouteImport } from './routes/comprends'
import { Route as DivisionRouteImport } from './routes/division'
import { Route as EnseignantRouteImport } from './routes/enseignant'
import { Route as ManipuleRouteImport } from './routes/manipule'
import { Route as MultiplicationRouteImport } from './routes/multiplication'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PratiqueRouteImport } from './routes/pratique'
import { Route as RepresenteRouteImport } from './routes/represente'
import { Route as SeanceRouteImport } from './routes/seance'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoustractionRouteImport } from './routes/soustraction'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as VerbesRouteImport } from './routes/verbes'
import { Route as MotsIndexRouteImport } from './routes/mots.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditionRoute = AdditionRouteImport.update({
  id: '/addition',
  path: '/addition',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprendsRoute = ComprendsRouteImport.update({
  id: '/comprends',
  path: '/comprends',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionRoute = DivisionRouteImport.update({
  id: '/division',
  path: '/division',
  getParentRoute: () => rootRouteImport,
} as any)
const EnseignantRoute = EnseignantRouteImport.update({
  id: '/enseignant',
  path: '/enseignant',
  getParentRoute: () => rootRouteImport,
} as any)
const ManipuleRoute = ManipuleRouteImport.update({
  id: '/manipule',
  path: '/manipule',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplicationRoute = MultiplicationRouteImport.update({
  id: '/multiplication',
  path: '/multiplication',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PratiqueRoute = PratiqueRouteImport.update({
  id: '/pratique',
  path: '/pratique',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresenteRoute = RepresenteRouteImport.update({
  id: '/represente',
  path: '/represente',
  getParentRoute: () => rootRouteImport,
} as any)
const SeanceRoute = SeanceRouteImport.update({
  id: '/seance',
  path: '/seance',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SoustractionRoute = SoustractionRouteImport.update({
  id: '/soustraction',
  path: '/soustraction',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const VerbesRoute = VerbesRouteImport.update({
  id: '/verbes',
  path: '/verbes',
  getParentRoute: () => rootRouteImport,
} as any)
const MotsIndexRoute = MotsIndexRouteImport.update({
  id: '/mots/',
  path: '/mots/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addition': typeof AdditionRoute
  '/auth': typeof AuthRoute
  '/comprends': typeof ComprendsRoute
  '/division': typeof DivisionRoute
  '/enseignant': typeof EnseignantRoute
  '/manipule': typeof ManipuleRoute
  '/multiplication': typeof MultiplicationRoute
  '/parent': typeof ParentRoute
  '/pratique': typeof PratiqueRoute
  '/represente': typeof RepresenteRoute
  '/seance': typeof SeanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soustraction': typeof SoustractionRoute
  '/tables': typeof TablesRoute
  '/verbes': typeof VerbesRoute
  '/mots/': typeof MotsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addition': typeof AdditionRoute
  '/auth': typeof AuthRoute
  '/comprends': typeof ComprendsRoute
  '/division': typeof DivisionRoute
  '/enseignant': typeof EnseignantRoute
  '/manipule': typeof ManipuleRoute
  '/multiplication': typeof MultiplicationRoute
  '/parent': typeof ParentRoute
  '/pratique': typeof PratiqueRoute
  '/represente': typeof RepresenteRoute
  '/seance': typeof SeanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soustraction': typeof SoustractionRoute
  '/tables': typeof TablesRoute
  '/verbes': typeof VerbesRoute
  '/mots': typeof MotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addition': typeof AdditionRoute
  '/auth': typeof AuthRoute
  '/comprends': typeof ComprendsRoute
  '/division': typeof DivisionRoute
  '/enseignant': typeof EnseignantRoute
  '/manipule': typeof ManipuleRoute
  '/multiplication': typeof MultiplicationRoute
  '/parent': typeof ParentRoute
  '/pratique': typeof PratiqueRoute
  '/represente': typeof RepresenteRoute
  '/seance': typeof SeanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soustraction': typeof SoustractionRoute
  '/tables': typeof TablesRoute
  '/verbes': typeof VerbesRoute
  '/mots/': typeof MotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addition'
    | '/auth'
    | '/comprends'
    | '/division'
    | '/enseignant'
    | '/manipule'
    | '/multiplication'
    | '/parent'
    | '/pratique'
    | '/represente'
    | '/seance'
    | '/sitemap.xml'
    | '/soustraction'
    | '/tables'
    | '/verbes'
    | '/mots/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addition'
    | '/auth'
    | '/comprends'
    | '/division'
    | '/enseignant'
    | '/manipule'
    | '/multiplication'
    | '/parent'
    | '/pratique'
    | '/represente'
    | '/seance'
    | '/sitemap.xml'
    | '/soustraction'
    | '/tables'
    | '/verbes'
    | '/mots'
  id:
    | '__root__'
    | '/'
    | '/addition'
    | '/auth'
    | '/comprends'
    | '/division'
    | '/enseignant'
    | '/manipule'
    | '/multiplication'
    | '/parent'
    | '/pratique'
    | '/represente'
    | '/seance'
    | '/sitemap.xml'
    | '/soustraction'
    | '/tables'
    | '/verbes'
    | '/mots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdditionRoute: typeof AdditionRoute
  AuthRoute: typeof AuthRoute
  ComprendsRoute: typeof ComprendsRoute
  DivisionRoute: typeof DivisionRoute
  EnseignantRoute: typeof EnseignantRoute
  ManipuleRoute: typeof ManipuleRoute
  MultiplicationRoute: typeof MultiplicationRoute
  ParentRoute: typeof ParentRoute
  PratiqueRoute: typeof PratiqueRoute
  RepresenteRoute: typeof RepresenteRoute
  SeanceRoute: typeof SeanceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoustractionRoute: typeof SoustractionRoute
  TablesRoute: typeof TablesRoute
  VerbesRoute: typeof VerbesRoute
  MotsIndexRoute: typeof MotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addition': {
      id: '/addition'
      path: '/addition'
      fullPath: '/addition'
      preLoaderRoute: typeof AdditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprends': {
      id: '/comprends'
      path: '/comprends'
      fullPath: '/comprends'
      preLoaderRoute: typeof ComprendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/division': {
      id: '/division'
      path: '/division'
      fullPath: '/division'
      preLoaderRoute: typeof DivisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enseignant': {
      id: '/enseignant'
      path: '/enseignant'
      fullPath: '/enseignant'
      preLoaderRoute: typeof EnseignantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manipule': {
      id: '/manipule'
      path: '/manipule'
      fullPath: '/manipule'
      preLoaderRoute: typeof ManipuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplication': {
      id: '/multiplication'
      path: '/multiplication'
      fullPath: '/multiplication'
      preLoaderRoute: typeof MultiplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratique': {
      id: '/pratique'
      path: '/pratique'
      fullPath: '/pratique'
      preLoaderRoute: typeof PratiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/represente': {
      id: '/represente'
      path: '/represente'
      fullPath: '/represente'
      preLoaderRoute: typeof RepresenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seance': {
      id: '/seance'
      path: '/seance'
      fullPath: '/seance'
      preLoaderRoute: typeof SeanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soustraction': {
      id: '/soustraction'
      path: '/soustraction'
      fullPath: '/soustraction'
      preLoaderRoute: typeof SoustractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verbes': {
      id: '/verbes'
      path: '/verbes'
      fullPath: '/verbes'
      preLoaderRoute: typeof VerbesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mots/': {
      id: '/mots/'
      path: '/mots'
      fullPath: '/mots/'
      preLoaderRoute: typeof MotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdditionRoute: AdditionRoute,
  AuthRoute: AuthRoute,
  ComprendsRoute: ComprendsRoute,
  DivisionRoute: DivisionRoute,
  EnseignantRoute: EnseignantRoute,
  ManipuleRoute: ManipuleRoute,
  MultiplicationRoute: MultiplicationRoute,
  ParentRoute: ParentRoute,
  PratiqueRoute: PratiqueRoute,
  RepresenteRoute: RepresenteRoute,
  SeanceRoute: SeanceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoustractionRoute: SoustractionRoute,
  TablesRoute: TablesRoute,
  VerbesRoute: VerbesRoute,
  MotsIndexRoute: MotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
